baseurl = "https://abbeyepage.github.io/"
languageCode = "en"
title = "Abbey Page"
theme = "Soho"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 50
enableEmoji = true
paginate = 5

[params]
title = "Abbey Page"
description = ""
images = ["images/profile.png"]
profilePicture = "images/profile.png"
copyright = "Abigail Page"
license = "MIT"
licenseURL = "https://opensource.org/licenses/MIT"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "#fc2803"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/alexandrevicenzi/soho"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/abbeyepage"

[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"

  [[menu.main]]
  name = "Projects"
  identifier = "projects"
  weight = 20
  url = "/projects/"

  [[menu.main]]
  name = "Publications"
  identifier = "publications"
  weight = 20
  url = "/publications/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
